development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { ":B2Uyx1cEdAx0bx54DR3WSycWR5URkN5O@redis-18997.c61.us-east-1-3.ec2.cloud.redislabs.com:18997" } %>
  channel_prefix: message_me_production
